version: "3"

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      # why change? default should be 2181
      - '2182:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - spark-network
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - spark-network
    volumes:
      - kafka:/data/kafka
    depends_on:
      - zookeeper
  spark-mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - spark-network
    command: mongod
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  spark-master:
    build:
      context: ./spark_master/
    ports:
      - "7077:7077"
      #- "4040:4040"
      - "8080:8080"
    networks:
      - spark-network
    depends_on:
      - spark-mongo
  spark-worker-1:
    build:
      context: ./pyspark_worker/
    ports:
      - "8081:8081"
    networks:
      - spark-network
    depends_on:
      - spark-mongo
networks:
  spark-network:
    external:
      name: spark-network
volumes:
  mongodb:
  mongodb_config:
  kafka: